// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvAYEIFo5cU-RIb3HqiD6gvadAmnnl7GY',
    appId: '1:833965396238:web:fff698b9d39b0c147f475f',
    messagingSenderId: '833965396238',
    projectId: 'expense-tracker-ada0e',
    authDomain: 'expense-tracker-ada0e.firebaseapp.com',
    databaseURL: 'https://expense-tracker-ada0e-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracker-ada0e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-gW9oTnlY_9EQPuV7vatMKtGKzTZe1cw',
    appId: '1:833965396238:android:2347ae0a3c294c4e7f475f',
    messagingSenderId: '833965396238',
    projectId: 'expense-tracker-ada0e',
    databaseURL: 'https://expense-tracker-ada0e-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracker-ada0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCapVQqmG6Rc4qo0fSXiEhvtrhOC0lIGdo',
    appId: '1:833965396238:ios:82305bf8f73690b87f475f',
    messagingSenderId: '833965396238',
    projectId: 'expense-tracker-ada0e',
    databaseURL: 'https://expense-tracker-ada0e-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracker-ada0e.appspot.com',
    iosClientId: '833965396238-fen7tef3v0vqb3f7nnvkvf4fnekjf97c.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCapVQqmG6Rc4qo0fSXiEhvtrhOC0lIGdo',
    appId: '1:833965396238:ios:727ff30c525221a47f475f',
    messagingSenderId: '833965396238',
    projectId: 'expense-tracker-ada0e',
    databaseURL: 'https://expense-tracker-ada0e-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracker-ada0e.appspot.com',
    iosClientId: '833965396238-p4hdas2etr8g29hgsc384o4hug5jpp2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );
}
